### ISSUE TITLE
Slide 18 - soft wrap option in Atom

### ISSUE THREAD

**Issue by joellecurcioCLC** [ladieslearningcode/llc-html-css-one-page#6]
I believe I have the most recent version of Atom and in my version the steps to set the soft wrap text option are slightly different. 
On the slides it is: 
Atom -> Preferences -> Settings -> Soft Wrap
For me it is:
Atom -> Preferences -> **Editor** -> Soft Wrap

Small difference but it took me a minute to find that option since I was looking off the slides. If this is in fact an update in Atom it may be worth updating the slides to avoid confusion. 

Thanks!

**Comment by jrmykolyn** [comment]
Hi @joellecurcioCLC,

I believe the issue you're describing has been fixed via [this commit](https://github.com/ladieslearningcode/llc-html-css-one-page/commit/13b7566951498c04edf367238448314e609578dc), which was merged into `master` via #10. When you have a moment, can you review and confirm/deny?

CC: @kasslent

**Comment by joellecurcioCLC** [comment]
Looks good, thank you!
