### ISSUE TITLE
slide 57 - google fonts site has changed (screenshots/steps out of date)

### ISSUE THREAD

**Issue by joellecurcioCLC** [ladieslearningcode/llc-html-css-one-page#9]
The Google Fonts site has changed, so the screenshots on this slide are out of date (for example, you no longer click "add to collection")

**Comment by jrmykolyn** [comment]
Hi @joellecurcioCLC,

I believe the issue you're describing has been fixed via [this commit](https://github.com/ladieslearningcode/llc-html-css-one-page/commit/ec51bee33937f1eb96290e0457ce09e1933f2a81), which was merged into `master` via #10. When you have a moment, can you review and confirm/deny?

CC: @kasslent

**Comment by joellecurcioCLC** [comment]
Looks good, thanks!
